### ISSUE TITLE
Error: Invalid Resource: The resource submitted could not be validated.

### ISSUE THREAD

**Issue by sfleif** [Sterc/mailchimpsubscribe#1]
Hi,

after submitting the form i get the following error:
`Invalid Resource: The resource submitted could not be validated. For field-specific details, see the 'errors' array.`

Any ideas how to solve this?
Thanks in advance.
Leif

**Comment by joeke** [comment]
@signalfeuer Should be fixed with the latest version 1.2.3: https://modx.com/extras/package/mailchimpforformit
